"""
CampaignIQ — Standalone AI Marketing Studio (Gradio UI)
Reuses the exact same ContentOptimizer and Scikit-Learn ML backend as the Streamlit app.
Features dual-engine copy generation (Local vs Gemini), live web research toggle,
ML approval scoring, side-by-side copy comparison, and NLP diagnostics.
"""

import os
import sys
import pandas as pd
import gradio as gr

# Ensure workspace root is in path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.content_optimizer import ContentOptimizer
from src.gemini_service import is_gemini_configured, get_gemini_status
from src.data_pipeline import TONES, AUDIENCES, CHANNELS

# Initialize singleton optimizer
optimizer = ContentOptimizer(model_path="models/campaign_success_model.joblib")

# Load catalog samples for quick selection
CATALOG_PATH = "data/cleaned_amazon.csv"
if os.path.exists(CATALOG_PATH):
    df_catalog = pd.read_csv(CATALOG_PATH)
    sample_products = df_catalog[['product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage', 'rating', 'about_product']].dropna().to_dict('records')
else:
    sample_products = []

product_choices = [p['product_name'][:75] for p in sample_products[:50]] if sample_products else ["Sample Fast Charging Cable"]


def populate_product(selected_name):
    if not selected_name:
        return "", "Computers&Accessories", 299.0, 599.0, 50.0, 4.2, "Durable braided cable"
    for p in sample_products:
        if p['product_name'].startswith(selected_name[:50]):
            return (
                p['product_name'],
                p['category'],
                float(p['discounted_price']),
                float(p['actual_price']),
                float(p['discount_percentage']),
                float(p['rating']),
                str(p.get('about_product', ''))[:200]
            )
    return selected_name, "Computers&Accessories", 299.0, 599.0, 50.0, 4.2, "High quality product"


def on_engine_change(engine_choice):
    """Disables Live Search toggle when Local Engine is selected since Local does not use Google Search."""
    if "Gemini" in engine_choice:
        return gr.update(interactive=True)
    else:
        return gr.update(interactive=False, value=False)


def run_campaign_studio(
    product_name: str,
    category: str,
    discounted_price: float,
    actual_price: float,
    discount_percentage: float,
    product_rating: float,
    features: str,
    tone: str,
    audience: str,
    channel: str,
    engine_choice: str,
    enable_grounding: bool
):
    if not product_name.strip():
        product_name = "Premium Product"
        
    mode = 'gemini' if "Gemini" in engine_choice else 'local'
    # Local engine never uses Google search grounding
    effective_grounding = enable_grounding if mode == 'gemini' else False
    
    result = optimizer.generate_optimized_copy(
        product_name=product_name,
        category=category,
        discounted_price=discounted_price,
        actual_price=actual_price,
        discount_percentage=discount_percentage,
        product_rating=product_rating,
        features=features,
        tone=tone,
        audience=audience,
        channel=channel,
        generator_mode=mode,
        enable_grounding=effective_grounding
    )
    
    # 1. Engine & Provenance Label
    source = result['generator_source']
    if source == 'gemini':
        if result.get('grounding_used'):
            engine_label = "🤖 Gemini + Google Search Grounding"
        else:
            engine_label = "🤖 Generated by Gemini"
    elif source == 'local_fallback':
        engine_label = f"⚙️ Generated by Local Template Engine (Fallback: {result.get('api_error', 'API unavailable')})"
    else:
        engine_label = "📐 Generated by Local Template Engine"
        
    # 2. Optimization Status Badge
    is_improved = result.get('is_improved', False)
    if is_improved:
        status_label = "✓ Optimized — ML approval improved"
        status_md = f"### Engine: **{engine_label}**\n### Status: <span style='color:#059669; font-weight:800;'>{status_label}</span>"
    else:
        status_label = "= No improvement required — baseline copy already has the highest verified ML score"
        status_md = f"### Engine: **{engine_label}**\n### Status: <span style='color:#475569; font-weight:700;'>{status_label}</span>"

    # 3. Scores & Verified Delta
    base = result['baseline']
    opt = result['optimized']
    comp = result['comparison']
    
    base_score_str = f"{comp['baseline_score']}% ({base['evaluation']['predicted_rating']})"
    opt_score_str = f"{comp['optimized_score']}% ({opt['evaluation']['predicted_rating']})"
    
    delta = result['delta_score']
    if delta > 0:
        delta_str = f"+{delta}% (Verified ML Improvement)"
    else:
        delta_str = "0.0% (Baseline already optimal)"
    
    # 4. Latencies (Separated clearly)
    gen_lat = result.get('gen_latency_ms', 0)
    inf_lat = result.get('inference_latency_ms', 0)
    tot_lat = result.get('total_latency_ms', result.get('latency_ms', 0))
    latency_str = f"Total: {tot_lat:.0f} ms | Generation: {gen_lat:.0f} ms | ML Inference: {inf_lat:.0f} ms"
    
    # 5. Baseline Copy Details
    base_pen = base['evaluation']['channel_fit_penalty']
    base_pen_str = "Optimal (No penalty)" if base_pen == 0 else f"Penalty: {base_pen:.2f}"
    base_text = (
        f"**Headline:**\n{base['headline']}\n\n"
        f"**Body:**\n> {base['copy']}\n\n"
        f"**Call to Action:**\n`{base['cta']}`\n\n"
        f"---\n"
        f"**Baseline Diagnostics:**\n"
        f"- **Word Count:** {comp['baseline_words']} words\n"
        f"- **Readability:** {comp['baseline_reading_ease']:.1f}/100 (Flesch Ease)\n"
        f"- **CTA:** {'Verified Action CTA' if comp['baseline_has_cta'] else 'Missing / Weak'}\n"
        f"- **Channel Fit:** {base_pen_str} (Target: {optimizer._get_ideal_length_str(channel)})"
    )
    
    # 6. Optimized Copy Details
    opt_pen = opt['evaluation']['channel_fit_penalty']
    opt_pen_str = "Optimal (No penalty)" if opt_pen == 0 else f"Penalty: {opt_pen:.2f}"
    copy_title = "### ✨ Optimized Copy" if is_improved else "### 📋 Final Copy (Baseline Retained)"
    opt_text = (
        f"{copy_title}\n\n"
        f"**Headline:**\n{opt['headline']}\n\n"
        f"**Body:**\n> {opt['copy']}\n\n"
        f"**Call to Action:**\n`{opt['cta']}`\n\n"
        f"---\n"
        f"**Optimized Diagnostics:**\n"
        f"- **Word Count:** {comp['optimized_words']} words\n"
        f"- **Readability:** {comp['optimized_reading_ease']:.1f}/100 (Flesch Ease)\n"
        f"- **CTA:** {'Verified Action CTA' if comp['optimized_has_cta'] else 'Missing / Weak'}\n"
        f"- **Channel Fit:** {opt_pen_str} (Target: {optimizer._get_ideal_length_str(channel)})"
    )
    
    # 7. Diagnostics & Recommendations
    diag_lines = []
    if result.get('diagnostic_improvements'):
        diag_lines.append("**Confirmed Diagnostic Improvements:**")
        for imp in result['diagnostic_improvements']:
            diag_lines.append(f"- 📈 {imp}")
        diag_lines.append("")
        
    recs = opt['evaluation'].get('recommendations', [])
    strengths = opt['evaluation'].get('strengths', [])
    
    if recs:
        diag_lines.append("**Actionable Recommendations:**")
        for r in recs:
            diag_lines.append(f"- ⚠️ {r}")
        diag_lines.append("")
    else:
        diag_lines.append("✅ Copy strictly satisfies all audience and channel constraints.\n")
        
    if strengths:
        diag_lines.append("**Detected Copy Strengths:**")
        for s in strengths:
            diag_lines.append(f"- ✨ {s}")
            
    diag_text = "\n".join(diag_lines)
    
    # 8. Optimization Result Rationale
    opt_result_text = f"**Optimization Result:** {result['optimization_reason']}"
    
    # 9. Grounding Sources (Google Search)
    if result.get('grounding_used'):
        sources = result.get('grounding_sources', [])
        if sources:
            src_md = "### 🌐 Web Sources / Grounding (Google Search)\n"
            for s in sources:
                t = s.get('title', 'Web Source')
                u = s.get('uri', '')
                if u:
                    src_md += f"- [{t}]({u})\n"
                else:
                    src_md += f"- {t}\n"
            sources_update = gr.update(visible=True, value=src_md)
        else:
            sources_update = gr.update(visible=True, value="### 🌐 Web Sources / Grounding (Google Search)\n*Web grounding used; source metadata was not returned by the API.*")
    else:
        sources_update = gr.update(visible=False, value="")
        
    return (
        status_md,
        base_score_str,
        opt_score_str,
        delta_str,
        latency_str,
        base_text,
        opt_text,
        diag_text,
        opt_result_text,
        sources_update
    )


# Build Polished Gradio UI
with gr.Blocks(title="CampaignIQ — AI Marketing Intelligence") as demo:
    gr.Markdown("# 🚀 CampaignIQ — Automated AI Content Generation & ML Optimization")
    gr.Markdown(
        "Generate and optimize high-converting marketing campaigns using **dual-engine architecture**: "
        "Real **Gemini API Generative AI** (with optional Google Search grounding) or **Local Template Engine**, "
        "paired with our trained **Scikit-Learn ML Model & Prescriptive NLP diagnostics**."
    )
    
    with gr.Row():
        # LEFT / INPUT PANEL
        with gr.Column(scale=5):
            gr.Markdown("### 📦 Input Panel & Campaign Strategy")
            product_dropdown = gr.Dropdown(
                label="Quick Pick Catalog Product (Real Amazon Catalog)",
                choices=product_choices,
                value=product_choices[0] if product_choices else None
            )
            
            p_name = gr.Textbox(label="Product Name", value="Ambrane 60W Fast Charging Cable")
            p_cat = gr.Textbox(label="Category", value="Computers&Accessories")
            
            with gr.Row():
                p_disc_price = gr.Number(label="Discounted Price (₹)", value=199.0)
                p_act_price = gr.Number(label="MSRP Price (₹)", value=499.0)
                p_disc_pct = gr.Number(label="Discount %", value=60.0)
                p_rating = gr.Number(label="Rating (1-5★)", value=4.3)
                
            p_features = gr.Textbox(
                label="Product Features / Description",
                value="Durable braided nylon, 60W Power Delivery, 480Mbps fast sync, 10000+ bend lifespan.",
                lines=2
            )
            
            with gr.Row():
                p_tone = gr.Dropdown(label="Marketing Tone", choices=TONES, value=TONES[0])
                p_audience = gr.Dropdown(label="Target Audience Persona", choices=AUDIENCES, value=AUDIENCES[0])
                p_channel = gr.Dropdown(label="Marketing Channel", choices=CHANNELS, value=CHANNELS[0])
                
            gr.Markdown("### ⚙️ Generation Engine")
            engine_radio = gr.Radio(
                label="Select Generation Engine (Gemini is fully optional)",
                choices=[
                    "Local Template Engine (Deterministic / Offline Fallback)",
                    "Gemini AI Engine (Generative AI Copywriter)"
                ],
                value="Gemini AI Engine (Generative AI Copywriter)" if is_gemini_configured() else "Local Template Engine (Deterministic / Offline Fallback)"
            )
            
            grounding_chk = gr.Checkbox(
                label="Use Live Web Research (Google Search Grounding via Gemini)",
                value=False,
                interactive=is_gemini_configured(),
                info="Enables live Google Search tools in Gemini API. Disabled when Local Engine is selected."
            )
            
            generate_btn = gr.Button("🚀 Generate & Optimize Campaign Copy", variant="primary", size="lg")
            
        # RIGHT / RESULTS PANEL
        with gr.Column(scale=7):
            gr.Markdown("### 📊 Results & Predictive Optimization Panel")
            status_box = gr.Markdown("### Engine: Ready\n### Status: Awaiting Generation")
            
            with gr.Row():
                out_base_score = gr.Textbox(label="Baseline ML Approval", interactive=False)
                out_opt_score = gr.Textbox(label="Optimized ML Approval", interactive=False)
                
            with gr.Row():
                out_delta = gr.Textbox(label="Verified Delta", interactive=False)
                out_latency = gr.Textbox(label="Runtime Latency", interactive=False)
                
            with gr.Row():
                with gr.Column():
                    gr.Markdown("#### 📝 Baseline Copy (Generated)")
                    out_base_copy = gr.Markdown("Generate a campaign to view baseline copy.")
                with gr.Column():
                    out_opt_copy = gr.Markdown("### ✨ Optimized Copy\nGenerate a campaign to view optimized copy.")
                    
            gr.Markdown("#### 🔬 Diagnostics")
            out_diagnostics = gr.Markdown("Diagnostics will appear here after generation.")
            
            gr.Markdown("#### ⚡ Optimization Result")
            out_opt_result = gr.Markdown("Optimization result details will appear here.")
            
            out_web_sources = gr.Markdown(visible=False)

    gr.Markdown("---")
    gr.Markdown(
        "**System Architecture Integrity:** "
        "Amazon product catalog is REAL (1,465 items). "
        "User approval model is trained on 6,500 SYNTHETIC campaign feedback logs. "
        "Engagement CTR/CVR are SIMULATED benchmarks. "
        "Dual-engine copy generation supports Gemini with Google Search grounding or 100% offline Local template fallback."
    )

    # Event handlers
    product_dropdown.change(
        fn=populate_product,
        inputs=[product_dropdown],
        outputs=[p_name, p_cat, p_disc_price, p_act_price, p_disc_pct, p_rating, p_features]
    )
    
    engine_radio.change(
        fn=on_engine_change,
        inputs=[engine_radio],
        outputs=[grounding_chk]
    )
    
    generate_btn.click(
        fn=run_campaign_studio,
        inputs=[
            p_name, p_cat, p_disc_price, p_act_price, p_disc_pct, p_rating, p_features,
            p_tone, p_audience, p_channel, engine_radio, grounding_chk
        ],
        outputs=[
            status_box, out_base_score, out_opt_score, out_delta, out_latency,
            out_base_copy, out_opt_copy, out_diagnostics, out_opt_result, out_web_sources
        ]
    )

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7860, share=False)
